docs: improve readme
expressjs/compression pull request #209
Opened 2024-12-05 20:52 UTC by bjohansebas

2025-01-08 22:46 UTC, wesleytodd requested changes
Other than my comments this is GREAT. Not sure if you want to just update or if you have strong reason for the other changes I asked about. If you do please let me know because I am very open to hearing differently! 🎉

2025-01-08 22:46 UTC, wesleytodd commented on README.md
> +[![NPM Install Size][npm-install-size-image]][npm-install-size-url]
In the past we have avoided this badge because it is misleading and often used to make bad decisions by folks who don't know what it really means in many contexts. I personally would prefer we keep with that policy.

2025-01-08 22:46 UTC, wesleytodd commented on README.md
> +npm install compression
This is tradition and I am not sure what our reason would be to remove it. Do you have a particular reason here I should know about?

2025-01-08 22:58 UTC, bjohansebas commented on README.md
> +npm install compression
I've always had to remove '$' when using the copy button provided by GitHub, so I think it would be good to remove it.

2025-01-08 23:00 UTC, bjohansebas commented on README.md
> +[![NPM Install Size][npm-install-size-image]][npm-install-size-url]
But it is being used in express, that's why I’m using it here

2025-01-08 23:16 UTC, wesleytodd commented on README.md
> +npm install compression
Ah, interesting. You might want to stop using that button lol. Never copy paste things into your terminal. There are some pretty well documented ways for folks to sneak in compromising security things. `iterm2` for examples requires you to enable pasting into the terminal for a reason.

2025-01-08 23:19 UTC, wesleytodd commented on README.md
> +[![NPM Install Size][npm-install-size-image]][npm-install-size-url]
OMG this was totally missed by me in this pr: https://github.com/expressjs/express/pull/5619

I would for sure have opposed it. I was much more focused on the other changes, this is why I dislike these big PRs, it is so easy to miss something. I will open a PR proposing we remove that.

2025-01-09 15:36 UTC, bjohansebas commented on README.md
> +[![NPM Install Size][npm-install-size-image]][npm-install-size-url]
Since I only added it to maintain consistency with Express, I will remove it.

2025-01-09 15:41 UTC, bjohansebas commented on README.md
> +npm install compression
That's true, i should stop copying and pasting, but i'm sure i'm not the only one. well, i’ll leave it for tradition's sake. Maybe you want to add it back to Express

2025-01-10 17:26 UTC, merged